---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rest-villains-config
  labels:
    app: rest-villains
    application: villains-service
    system: quarkus-super-heroes
data:
  quarkus.hibernate-orm.database.generation: validate
  quarkus.hibernate-orm.sql-load-script: no-file
  quarkus.datasource.jdbc.url: jdbc:otel:postgresql://villains-db:5432/villains_database
  quarkus.opentelemetry.tracer.exporter.otlp.endpoint: http://otel-collector:4317
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: rest-villains-config-creds
  labels:
    app: rest-villains
    application: villains-service
    system: quarkus-super-heroes
data:
  quarkus.datasource.username: c3VwZXJiYWQ=
  quarkus.datasource.password: c3VwZXJiYWQ=
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: villains-db-config
  labels:
    app: villains-db
    application: villains-service
    system: quarkus-super-heroes
data:
  POSTGRESQL_DATABASE: dmlsbGFpbnNfZGF0YWJhc2U=
  POSTGRESQL_USERNAME: c3VwZXJiYWQ=
  POSTGRESQL_PASSWORD: c3VwZXJiYWQ=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: villains-db-init
  labels:
    app: villains-db
    application: villains-service
    system: quarkus-super-heroes
data:
  get-data.sh: |-
    #!/bin/bash
    
    curl https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/main/rest-villains/deploy/db-init/initialize-tables.sql --output /docker-entrypoint-initdb.d/1-init-tables.sql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: villains-db
    application: villains-service
    system: quarkus-super-heroes
    app.kubernetes.io/part-of: villains-service
    app.openshift.io/runtime: postgresql
  name: villains-db
spec:
  replicas: 1
  selector:
    matchLabels:
      name: villains-db
  template:
    metadata:
      labels:
        application: villains-service
        name: villains-db
    spec:
      containers:
        - image: bitnami/postgresql:14
          name: villains-db
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: villains-db-config
          volumeMounts:
            - name: villains-db-data
              mountPath: /bitnami/postgresql
            - name: villains-db-init
              mountPath: /docker-entrypoint-preinitdb.d
          resources:
            limits:
              memory: 128Mi
            requests:
              memory: 32Mi
      volumes:
        - name: villains-db-data
          emptyDir: {}
        - name: villains-db-init
          configMap:
            name: villains-db-init
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: villains-db
    application: villains-service
    system: quarkus-super-heroes
  name: villains-db
spec:
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    name: villains-db
  type: ClusterIP
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: rest-villains
spec:
  lookupPolicy:
    local: false
  tags:
    - name: java11-latest
      annotations: null
      from:
        kind: DockerImage
        name: 'quay.io/quarkus-super-heroes/rest-villains:java11-latest'
      importPolicy: {}
      referencePolicy:
        type: Source
    - name: java17-latest
      annotations: null
      from:
        kind: DockerImage
        name: 'quay.io/quarkus-super-heroes/rest-villains:java17-latest'
      importPolicy: { }
      referencePolicy:
        type: Source
    - name: native-java11-latest
      annotations: null
      from:
        kind: DockerImage
        name: 'quay.io/quarkus-super-heroes/rest-villains:native-java11-latest'
      importPolicy: { }
      referencePolicy:
        type: Source
    - name: native-java17-latest
      annotations: null
      from:
        kind: DockerImage
        name: 'quay.io/quarkus-super-heroes/rest-villains:native-java17-latest'
      importPolicy: { }
      referencePolicy:
        type: Source
